language: generic 
sudo: required
servies: 
  - docker

before_install:
  - docker build -t abhibhat97/docker-react1 -f Dockerfile.dev .

script:
  - docker run -e CI=true abhibhat97/docker-react1 npm run test

deploy:
  provider: elasticbeanstalk  
  region: "us-east-1"
  app: "test-docker"
  env: "TestDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-730058774163"
  bucket_path: "test-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY