language: generic 
sudo: required
servies: 
  - docker

before_install:
  - docker build -t abhibhat97/docker-react1 -f Dockerfile.dev .

script:
  - docker run -e CI=true abhibhat97/docker-react1 npm run test